# Generated by Django 2.2.24 on 2021-12-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211203_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
